#!/bin/bash

WEBAPPS=/var/lib/tomcat7/webapps
NAME=teamview-2.0.0-SNAPSHOT

/etc/init.d/tomcat7 stop
rm -rf $WEBAPPS/teamview $WEBAPPS/teamview.war
cp target/$NAME.war $WEBAPPS/teamview.war
/etc/init.d/tomcat7 start


